services:
  imams:
    # Name of the image to be built
    image: imams
    # Build the image from the Dockerfile in the current directory
    build:
      # Dockerfile is in the current directory
      context: .
      # Name of the Dockerfile
      dockerfile: Dockerfile
    # Restart policy
    environment:
      DJANGO_SETTINGS_MODULE: "imams.settings"
      DEBUG: 1
      TZ: "Europe/London"
      DJANGO_SUPERUSER_PASSWORD: p
      DJANGO_SUPERUSER_USERNAME: a
      DJANGO_SUPERUSER_EMAIL: a@g.com
    restart: unless-stopped
    # Port mapping
    # This means that the port 8000 of the host will be mapped to the port 8000 of the container.
    ports:
      - "8000:8000"
    # Volume mapping
    volumes:
      - .:/app
    # Service dependencies
    depends_on:
      - db
    # Runtime command
    # Please check the Docker Tutorial 1 for more details.
    entrypoint: ["./entrypoint.sh"]

  # "db" service
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: p
      MYSQL_DATABASE: p
      MYSQL_USER: p
      MYSQL_PASSWORD: p
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# Volumes
volumes:
  # "db_data" volume definition
  db_data:
